"""Initial catalog and workflow schema, frozen from the pre-migration 32-table model."""

import sqlalchemy as sa
from alembic import context, op
from app.config import settings

revision = "20260913_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    SCHEMA = context.config.attributes.get("schema", settings.database_schema)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_codes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("code_system", sa.String(length=50), nullable=False),
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_system", "code", name="uq_billing_code"),
        schema=SCHEMA,
    )
    op.create_table(
        "chat_feedback",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("response_id", sa.String(length=120), nullable=True),
        sa.Column("session_hash", sa.String(length=64), nullable=False),
        sa.Column("rating", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("redacted_question", sa.Text(), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=True),
        sa.Column("sub_intent", sa.String(length=80), nullable=True),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.create_table(
        "data_sources",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        schema=SCHEMA,
    )
    op.create_table(
        "faq_candidates",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("canonical_question", sa.Text(), nullable=False),
        sa.Column("normalized_question", sa.Text(), nullable=False),
        sa.Column("canonical_answer", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=True),
        sa.Column("sub_intent", sa.String(length=80), nullable=True),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("positive_count", sa.Integer(), nullable=False),
        sa.Column("negative_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
        schema=SCHEMA,
    )
    op.create_table(
        "handoff_requests",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("public_id", sa.String(length=40), nullable=False),
        sa.Column("session_hash", sa.String(length=64), nullable=False),
        sa.Column("inquiry_type", sa.String(length=50), nullable=False),
        sa.Column("requester_name_encrypted", sa.Text(), nullable=False),
        sa.Column("phone_encrypted", sa.Text(), nullable=False),
        sa.Column("organization_encrypted", sa.Text(), nullable=True),
        sa.Column("content_encrypted", sa.Text(), nullable=False),
        sa.Column("related_refs", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        schema=SCHEMA,
    )
    op.create_table(
        "methods",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("method_group", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name"),
        schema=SCHEMA,
    )
    op.create_table(
        "specimens",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("canonical_name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("specimen_group", sa.String(length=80), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name"),
        schema=SCHEMA,
    )
    op.create_table(
        "taxonomy_terms",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("taxonomy", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_url", sa.String(length=1500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("taxonomy", "normalized_name", name="uq_taxonomy_term"),
        schema=SCHEMA,
    )
    op.create_table(
        "vector_index_items",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("local_ref", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.String(length=120), nullable=False),
        sa.Column("vector_store_id", sa.String(length=160), nullable=False),
        sa.Column("openai_file_id", sa.String(length=160), nullable=True),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("index_status", sa.String(length=30), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("usage_bytes", sa.BigInteger(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vector_store_id", "local_ref", name="uq_vector_index_store_ref"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_vector_index_file",
        "vector_index_items",
        ["vector_store_id", "openai_file_id"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "ix_vector_index_status",
        "vector_index_items",
        ["vector_store_id", "index_status"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_table(
        "containers",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_external_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("additive", sa.Text(), nullable=True),
        sa.Column("major_tests_text", sa.Text(), nullable=True),
        sa.Column("collection_volume_text", sa.Text(), nullable=True),
        sa.Column("storage_text", sa.Text(), nullable=True),
        sa.Column("caution_text", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=1500), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("missing_runs", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "source_external_key", name="uq_container_source_key"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_containers_normalized_name", "containers", ["normalized_name"], unique=False, schema=SCHEMA
    )
    op.create_table(
        "dataset_sync_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("dataset", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_requested", sa.Integer(), nullable=False),
        sa.Column("pages_succeeded", sa.Integer(), nullable=False),
        sa.Column("records_found", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_unchanged", sa.Integer(), nullable=False),
        sa.Column("records_deactivated", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_expected", sa.Integer(), nullable=False),
        sa.Column("pages_requested", sa.Integer(), nullable=False),
        sa.Column("pages_succeeded", sa.Integer(), nullable=False),
        sa.Column("records_found", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_unchanged", sa.Integer(), nullable=False),
        sa.Column("records_deactivated", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.create_table(
        "preservative_guides",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_name", sa.String(length=1000), nullable=False),
        sa.Column("normalized_test_name", sa.String(length=1000), nullable=False),
        sa.Column("light_protection", sa.String(length=100), nullable=True),
        sa.Column("acetic_acid_50", sa.String(length=100), nullable=True),
        sa.Column("hcl_6n", sa.String(length=100), nullable=True),
        sa.Column("boric_acid_10g", sa.String(length=100), nullable=True),
        sa.Column("sodium_carbonate_5g", sa.String(length=100), nullable=True),
        sa.Column("no_preservative", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "normalized_test_name", name="uq_preservative_test"),
        schema=SCHEMA,
    )
    op.create_table(
        "public_documents",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_external_key", sa.String(length=220), nullable=False),
        sa.Column("document_type", sa.String(length=50), nullable=False),
        sa.Column("board_id", sa.String(length=50), nullable=True),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("normalized_title", sa.String(length=1000), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=1500), nullable=True),
        sa.Column("source_url", sa.String(length=1500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("missing_runs", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "source_external_key", name="uq_public_document_source_key"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_public_documents_normalized_title",
        "public_documents",
        ["normalized_title"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_index(
        "ix_public_documents_type_date",
        "public_documents",
        ["document_type", "published_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_table(
        "service_locations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_external_key", sa.String(length=220), nullable=False),
        sa.Column("location_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("region", sa.String(length=200), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=200), nullable=True),
        sa.Column("fax", sa.String(length=200), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("source_url", sa.String(length=1500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "source_external_key", name="uq_location_source_key"),
        schema=SCHEMA,
    )
    op.create_table(
        "site_routes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("path", sa.String(length=1500), nullable=False),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("normalized_label", sa.String(length=500), nullable=False),
        sa.Column("parent_path", sa.String(length=1500), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("menu_order", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=1500), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "path", name="uq_site_route_path"),
        schema=SCHEMA,
    )
    op.create_table(
        "source_pages",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("page_type", sa.String(length=50), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "url", name="uq_source_page_url"),
        schema=SCHEMA,
    )
    op.create_table(
        "taxonomy_relations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("parent_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("child_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["child_id"],
            [f"{SCHEMA}.taxonomy_terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            [f"{SCHEMA}.taxonomy_terms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "child_id", "relation_type", name="uq_taxonomy_relation"),
        schema=SCHEMA,
    )
    op.create_table(
        "tests",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_test_code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("normalized_name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("missing_runs", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id", "source_test_code", name="uq_test_source_code"),
        schema=SCHEMA,
    )
    op.create_index("ix_tests_normalized_name", "tests", ["normalized_name"], unique=False, schema=SCHEMA)
    op.create_table(
        "container_aliases",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("container_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("alias", sa.String(length=500), nullable=False),
        sa.Column("normalized_alias", sa.String(length=500), nullable=False),
        sa.Column("alias_type", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_id"],
            [f"{SCHEMA}.containers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_id", "normalized_alias", name="uq_container_alias"),
        schema=SCHEMA,
    )
    op.create_table(
        "container_test_mentions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("container_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("mention_text", sa.String(length=1000), nullable=False),
        sa.Column("normalized_mention", sa.String(length=1000), nullable=False),
        sa.Column("test_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["container_id"],
            [f"{SCHEMA}.containers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            [f"{SCHEMA}.tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_id", "normalized_mention", name="uq_container_mention"),
        schema=SCHEMA,
    )
    op.create_table(
        "document_attachments",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("document_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_external_key", sa.String(length=300), nullable=False),
        sa.Column("file_name", sa.String(length=1000), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=True),
        sa.Column("download_url", sa.String(length=2000), nullable=True),
        sa.Column("preview_url", sa.String(length=2000), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            [f"{SCHEMA}.public_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "source_external_key", name="uq_document_attachment_source_key"),
        schema=SCHEMA,
    )
    op.create_table(
        "entity_revisions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("sync_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            [f"{SCHEMA}.dataset_sync_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entity_type", "entity_id", "content_hash", name="uq_entity_revision"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_entity_revisions_entity",
        "entity_revisions",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_table(
        "test_aliases",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("alias", sa.String(length=500), nullable=False),
        sa.Column("normalized_alias", sa.String(length=500), nullable=False),
        sa.Column("alias_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_id"],
            [f"{SCHEMA}.tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_id", "normalized_alias", name="uq_test_alias"),
        schema=SCHEMA,
    )
    op.create_table(
        "test_taxonomy_links",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("taxonomy_term_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("relation_type", sa.String(length=50), nullable=False),
        sa.Column("matched_text", sa.String(length=500), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["taxonomy_term_id"],
            [f"{SCHEMA}.taxonomy_terms.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            [f"{SCHEMA}.tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_id", "taxonomy_term_id", "relation_type", name="uq_test_taxonomy_link"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_test_taxonomy_links_term",
        "test_taxonomy_links",
        ["taxonomy_term_id", "test_id"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_table(
        "test_variants",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_sample_code", sa.String(length=100), nullable=False),
        sa.Column("source_row_key", sa.String(length=220), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("method_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("specimen_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("container_text", sa.String(length=500), nullable=True),
        sa.Column("billing_code_text", sa.String(length=500), nullable=True),
        sa.Column("schedule_text", sa.String(length=300), nullable=True),
        sa.Column("schedule_days", sa.JSON(), nullable=False),
        sa.Column("schedule_shift", sa.String(length=30), nullable=True),
        sa.Column("tat_text", sa.String(length=200), nullable=True),
        sa.Column("tat_min_days", sa.Float(), nullable=True),
        sa.Column("tat_max_days", sa.Float(), nullable=True),
        sa.Column("detail_url", sa.String(length=1000), nullable=False),
        sa.Column("source_page_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("missing_runs", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["method_id"],
            [f"{SCHEMA}.methods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_page_id"],
            [f"{SCHEMA}.source_pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specimen_id"],
            [f"{SCHEMA}.specimens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            [f"{SCHEMA}.tests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_id", "source_sample_code", name="uq_test_variant_sample"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_test_variants_source_row_key", "test_variants", ["source_row_key"], unique=False, schema=SCHEMA
    )
    op.create_index(
        "ix_test_variants_tat", "test_variants", ["tat_min_days", "tat_max_days"], unique=False, schema=SCHEMA
    )
    op.create_table(
        "attachment_contents",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("attachment_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("extraction_status", sa.String(length=30), nullable=False),
        sa.Column("extractor", sa.String(length=80), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            [f"{SCHEMA}.document_attachments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attachment_id", name="uq_attachment_content"),
        schema=SCHEMA,
    )
    op.create_table(
        "source_records",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("ingestion_run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("data_source_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_page_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("external_key", sa.String(length=220), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("test_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("test_variant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_source_id"],
            [f"{SCHEMA}.data_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            [f"{SCHEMA}.ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_page_id"],
            [f"{SCHEMA}.source_pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            [f"{SCHEMA}.tests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_variant_id"],
            [f"{SCHEMA}.test_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "data_source_id", "external_key", "content_hash", name="uq_source_record_version"
        ),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_source_records_current",
        "source_records",
        ["data_source_id", "external_key", "is_current"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_table(
        "test_billing_codes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_variant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("billing_code_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["billing_code_id"],
            [f"{SCHEMA}.billing_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_variant_id"],
            [f"{SCHEMA}.test_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_variant_id", "billing_code_id", name="uq_variant_billing"),
        schema=SCHEMA,
    )
    op.create_table(
        "test_public_details",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_variant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_page_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("fields_json", sa.JSON(), nullable=False),
        sa.Column("container_json", sa.JSON(), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("fetch_status", sa.String(length=30), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_page_id"],
            [f"{SCHEMA}.source_pages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_variant_id"],
            [f"{SCHEMA}.test_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("test_variant_id", name="uq_test_public_detail_variant"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_test_public_details_status",
        "test_public_details",
        ["fetch_status", "last_success_at"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_table(
        "attachment_chunks",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "attachment_content_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section_label", sa.String(length=300), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_content_id"],
            [f"{SCHEMA}.attachment_contents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attachment_content_id", "sequence", name="uq_attachment_chunk_sequence"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_attachment_chunks_content",
        "attachment_chunks",
        ["attachment_content_id", "sequence"],
        unique=False,
        schema=SCHEMA,
    )
    op.create_table(
        "test_revisions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("test_variant_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("source_record_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            [f"{SCHEMA}.source_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            [f"{SCHEMA}.tests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_variant_id"],
            [f"{SCHEMA}.test_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=SCHEMA,
    )
    op.create_index(
        "ix_test_revisions_test_created",
        "test_revisions",
        ["test_id", "created_at"],
        unique=False,
        schema=SCHEMA,
    )
    # ### end Alembic commands ###

    # A private schema has no browser/API grants, including projects with legacy defaults.
    op.execute(f'REVOKE ALL ON SCHEMA "{SCHEMA}" FROM PUBLIC')
    op.execute(f'REVOKE ALL ON ALL TABLES IN SCHEMA "{SCHEMA}" FROM PUBLIC')
    op.execute(f'REVOKE ALL ON ALL SEQUENCES IN SCHEMA "{SCHEMA}" FROM PUBLIC')
    for role in ("anon", "authenticated", "service_role"):
        op.execute(f"""DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN
                REVOKE ALL ON SCHEMA "{SCHEMA}" FROM "{role}";
                REVOKE ALL ON ALL TABLES IN SCHEMA "{SCHEMA}" FROM "{role}";
                REVOKE ALL ON ALL SEQUENCES IN SCHEMA "{SCHEMA}" FROM "{role}";
            END IF;
        END $$""")


def downgrade():
    raise RuntimeError(
        "Initial data schema cannot be dropped automatically; restore a verified backup instead"
    )
